services:
  - type: web
    name: retropulse
    env: node
    region: frankfurt
    buildCommand: npm run render-build
    startCommand: cd backend && npm start
    domains:
      - ahmedmakled.com
      - www.ahmedmakled.com
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://ahmedmakled.com
      - key: ALLOWED_ORIGINS
        value: https://ahmedmakled.com,https://www.ahmedmakled.com
      - key: DEBUG
        value: "app:*"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://ahmedmakled.com, https://www.ahmedmakled.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,PATCH,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Origin,Content-Type,Accept,Authorization
    healthCheckPath: /api/health
    autoDeploy: true